In [11]:
import pandas as pd
from scipy.stats import chi2_contingency, f_oneway
from scipy.stats import ttest_ind

In [12]:
census = pd.read_excel("../data/Assignment-census_income.xlsx", sheet_name="census_income")
census.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,Y.income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [13]:
census.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  str
 14  Y.income        32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [14]:
census.describe()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [15]:
# ho: There is race gap based on education 
# h1: There is a race gap based on education

race_education = pd.crosstab(census["education"], census["race"])
race_education

race          Amer-Indian-Eskimo  Asian-Pac-Islander  Black  Other  White
education
10th                          16                  13    133      9    762
11th                          14                  21    153     10    977
12th                           5                   9     70     14    335
1st-4th                        4                   5     16      9    134
5th-6th                        2                  18     21     13    279
7th-8th                        9                  11     56     17    553
9th                            5                   9     89      8    403
Assoc-acdm                     8                  29    107      8    915
Assoc-voc                     19                  38    112      6   1207
Bachelors                     21                 289    330     33   4682
Doctorate                      3                  28     11      2    369
HS-grad                      119                 226   1174     78   8904
Masters                        5                  88     86      7   1537
Preschool                      0                   6      5      2     38
Prof-school                    2                  41     15      4    514
Some-college                  79                 208    746     51   6207

In [16]:
res = chi2_contingency(race_education)
chi2, p, dof, expected = res
print("Chi2 Statistic:", chi2)
print("P-Value:", p)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:", expected)
print("Chi2:", chi2)

Chi2 Statistic: 730.6712962254584
P-Value: 5.547319569858433e-116
Degrees of Freedom: 60
Expected Frequencies: [[8.91136636e+00 2.97714137e+01 8.95148183e+01 7.76520991e+00
  7.97037192e+02]
 [1.12227819e+01 3.74934738e+01 1.12733024e+02 9.77933724e+00
  1.00377138e+03]
 [4.13571451e+00 1.38167440e+01 4.15433187e+01 3.60378981e+00
  3.69900433e+02]
 [1.60461902e+00 5.36076902e+00 1.61184239e+01 1.39823715e+00
  1.43517951e+02]
 [3.18058413e+00 1.06258100e+01 3.19490188e+01 2.77150579e+00
  2.84473081e+02]
 [6.17014219e+00 2.06134332e+01 6.19791775e+01 5.37655477e+00
  5.51860692e+02]
 [4.90937011e+00 1.64014004e+01 4.93147016e+01 4.27793987e+00
  4.39096588e+02]
 [1.01912411e+01 3.40472651e+01 1.02371180e+02 8.88047050e+00
  9.11509843e+02]
 [1.31999017e+01 4.40987070e+01 1.32593225e+02 1.15021652e+01
  1.18060600e+03]
 [5.11472314e+01 1.70874512e+02 5.13774761e+02 4.45688093e+01
  4.57463469e+03]
 [3.94468843e+00 1.31785572e+01 3.96244587e+01 3.43733301e+00
  3.52814963e+02]
 [1.00298240e+02 3.35079973e+02 1.00749744e+03 8.73981450e+01
  8.97072621e+03]
 [1.64568963e+01 5.49797918e+01 1.65309788e+02 1.43402537e+01
  1.47191327e+03]
 [4.87116489e-01 1.62737631e+00 4.89309296e+00 4.24464851e-01
  4.35679494e+01]
 [5.50155094e+00 1.83797795e+01 5.52631676e+01 4.79395596e+00
  4.92061546e+02]
 [6.96385553e+01 2.32650994e+02 6.99520408e+02 6.06818280e+01
  6.22850822e+03]]
Chi2: 730.6712962254584

In [17]:
census.groupby("workclass").count()

,age,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,Y.income
workclass,,,,,,,,,,,,,,
?,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836
Federal-gov,960,960,960,960,960,960,960,960,960,960,960,960,960,960
Local-gov,2093,2093,2093,2093,2093,2093,2093,2093,2093,2093,2093,2093,2093,2093
Never-worked,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Private,22696,22696,22696,22696,22696,22696,22696,22696,22696,22696,22696,22696,22696,22696
Self-emp-inc,1116,1116,1116,1116,1116,1116,1116,1116,1116,1116,1116,1116,1116,1116
Self-emp-not-inc,2541,2541,2541,2541,2541,2541,2541,2541,2541,2541,2541,2541,2541,2541
State-gov,1298,1298,1298,1298,1298,1298,1298,1298,1298,1298,1298,1298,1298,1298
Without-pay,14,14,14,14,14,14,14,14,14,14,14,14,14,14

In [18]:

# census = census.applymap(lambda x: x.strip() if x.dtype == "str" else x)
# census_Federal_gov = census[census["workclass"] == " Federal-gov"]["education.num"]
# # print(census_Federal_gov)
# census_Local_gov = census[census["workclass"] == " Local-gov"]["education.num"]
# # print(census_Federal_gov)

# census_never_worked = census[census["workclass"] == " Never-worked"]["education.num"]
# census_private = census[census["workclass"] == " Private"]["education.num"]
# census_self_emp_inc = census[census["workclass"] == " Self-emp-inc"]["education.num"]
# census_self_emp_not_inc = census[census["workclass"] == " Self-emp-not-inc"]["education.num"]
# census_state_gov = census[census["workclass"] == " State-gov"]["education.num"]
# census_without_pay = census[census["workclass"] == " Without-pay"]["education.num"]
# census_question_mark = census[census["workclass"] == " ?"]["education.num"]  

# f_statistic, p_value = f_oneway(census_Federal_gov, census_Local_gov, census_never_worked, census_private, census_self_emp_inc, census_self_emp_not_inc, census_state_gov, census_without_pay, census_question_mark)
# p_value

In [60]:
#task 9
from scipy.stats import ttest_ind
import numpy as np
from statsmodels.stats.weightstats import ztest
less_group = census[census["Y.income" ]== " <=50K"]["education.num"]
less_group_500 = np.random.choice(less_group,500)
less_group.info()
great_group =  census[census["Y.income" ]== " >50K"]["education.num"]
great_group_500 = np.random.choice(great_group,500)

great_group.info()
res =ttest_ind(less_group_500,great_group_500,equal_var=True )
stat, pvalue = res
print("t-test",stat,f"{pvalue:.20e}")
# pvalue

rest_z = ztest(less_group,great_group)
print("z-test",rest_z)

<class 'pandas.Series'>
Index: 24720 entries, 0 to 32559
Series name: education.num
Non-Null Count  Dtype
--------------  -----
24720 non-null  int64
dtypes: int64(1)
memory usage: 386.2 KB
<class 'pandas.Series'>
Index: 7841 entries, 7 to 32560
Series name: education.num
Non-Null Count  Dtype
--------------  -----
7841 non-null   int64
dtypes: int64(1)
memory usage: 122.5 KB
t-test -13.944326554757861 1.64977173945656603312e-40
z-test (np.float64(-64.18797223551665), np.float64(0.0))

In [81]:
census.info()

marital_income = pd.crosstab( census["marital.status"],census["Y.income"])
print(marital_income)
marital_income["lt5k"] = marital_income[" <=50K"] / (marital_income[" <=50K"]  +marital_income[" >50K"])
marital_income["gt5k"] = marital_income[" >50K"] / (marital_income[" <=50K"] + marital_income[" >50K"])

print(marital_income)
marital_income_normal = marital_income[["lt5k","gt5k"]]
res = chi2_contingency(marital_income_normal)
print("Chi-test", res)
print("p-value",f"{res.pvalue:.20}")

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  str
 14  Y.income        32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB
Y.income               <=50K  >50K
marital.status
Divorced                3980   463
Married-AF-spouse         13    10
Married-civ-spouse      8284  6692
Married-spouse-absent    384    34
Never-married          10192   491
Separated                959    66
Widowed                  908    85
Y.income                <=50K   >50K      lt5k      gt5k
marital.status
Divorced                 3980    463  0.895791  0.104209
Married-AF-spouse          13     10  0.565217  0.434783
Married-civ-spouse       8284   6692  0.553152  0.446848
Married-spouse-absent     384     34  0.918660  0.081340
Never-married           10192    491  0.954039  0.045961
Separated                 959     66  0.935610  0.064390
Widowed                   908     85  0.914401  0.085599
Chi-test Chi2ContingencyResult(statistic=np.float64(1.2972330969148578), pvalue=np.float64(0.9718100528233138), dof=6, expected_freq=array([[0.81955289, 0.18044711],
       [0.81955289, 0.18044711],
       [0.81955289, 0.18044711],
       [0.81955289, 0.18044711],
       [0.81955289, 0.18044711],
       [0.81955289, 0.18044711],
       [0.81955289, 0.18044711]]))
p-value 0.97181005282331378581