In [22]:
import pandas as pd
# from sklearn.encode import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

In [23]:
df = pd.read_csv("./data/loan_preprocessed.csv")
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,0,5849,0.0,146.412162,360.0,1.0,1,0.0,0.0,1.0
1,1,1,1,1,0,4583,1508.0,128.000000,360.0,1.0,0,1.0,0.0,0.0
2,1,1,0,1,1,3000,0.0,66.000000,360.0,1.0,1,0.0,0.0,1.0
3,1,1,0,0,0,2583,2358.0,120.000000,360.0,1.0,1,0.0,0.0,1.0
4,1,0,0,1,0,6000,0.0,141.000000,360.0,1.0,1,0.0,0.0,1.0

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 601 entries, 0 to 600
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   601 non-null    int64
 1   Married                  601 non-null    int64
 2   Dependents               601 non-null    int64
 3   Education                601 non-null    int64
 4   Self_Employed            601 non-null    int64
 5   ApplicantIncome          601 non-null    int64
 6   CoapplicantIncome        601 non-null    float64
 7   LoanAmount               601 non-null    float64
 8   Loan_Amount_Term         601 non-null    float64
 9   Credit_History           601 non-null    float64
 10  Loan_Status              601 non-null    int64
 11  Property_Area_Rural      601 non-null    float64
 12  Property_Area_Semiurban  601 non-null    float64
 13  Property_Area_Urban      601 non-null    float64
dtypes: float64(7), int64(7)
memory usage: 65.9 KB

In [27]:
ms = MinMaxScaler(clip=True)
columns_to_scale = ["ApplicantIncome", "CoapplicantIncome", "LoanAmount","Loan_Amount_Term"]
ms.fit(df[columns_to_scale])
df[columns_to_scale] = ms.transform(df[columns_to_scale])

df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,0,0.240942,0.000000,0.214372,0.74359,1.0,1,0.0,0.0,1.0
1,1,1,1,1,0,0.187418,0.167929,0.185647,0.74359,1.0,0,1.0,0.0,0.0
2,1,1,0,1,1,0.120492,0.000000,0.088924,0.74359,1.0,1,0.0,0.0,1.0
3,1,1,0,0,0,0.102862,0.262584,0.173167,0.74359,1.0,1,0.0,0.0,1.0
4,1,0,0,1,0,0.247326,0.000000,0.205928,0.74359,1.0,1,0.0,0.0,1.0